SELECT USER
FROM DUAL;
--==>> SCOTT

DROP SEQUENCE SCORESEQ;

DROP TABLE TBL_SCORE PURGE;

CREATE TABLE TBL_SCORE
( SID   NUMBER
, NAME  VARCHAR(30) NOT NULL
, KOR   NUMBER 
, ENG   NUMBER
, MAT   NUMBER
, CONSTRAINT SCORE_SID_PK PRIMARY KEY(SID)
);

CREATE SEQUENCE SCORESEQ;

INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '±èÅÂ¹Î', 90, 80, 70)
;
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, 'ÃÖµ¿Çö', 90, 88, 70)
;

SELECT SID, NAME
     , KOR, ENG, MAT
     , (KOR + ENG + MAT) AS TOT
     , ROUND( ( (KOR + ENG + MAT)/3.0),1) AS AVG
FROM TBL_SCORE
ORDER BY SID;
--> ÇÑ ÁÙ ±¸¼º
SELECT SID, NAME, KOR, ENG, MAT, (KOR + ENG + MAT) AS TOT, ROUND( ( (KOR + ENG + MAT)/3.0),1) AS AVG FROM TBL_SCORE ORDER BY SID
;
--==>>
/*
1	±èÅÂ¹Î	90	80	70	240	80
2	ÃÖµ¿Çö	90	88	70	248	82.7
*/

SELECT COUNT(*) AS COUNT
FROM TBL_SCORE;
--> ÇÑ ÁÙ ±¸¼º
SELECT COUNT(*) AS COUNT FROM TBL_SCORE
;
--==>> 2

COMMIT;